### ISSUE TITLE
Mockup for user tile after adding a user

### ISSUE THREAD

**Issue by gakshay** [gakshay/hookhook#20]

**Comment by guptapiyush** [comment]
![mockup 1 - 90 image](https://cloud.githubusercontent.com/assets/3889292/7238069/c93814b8-e754-11e4-8eb2-3511ba120ccc.png)

I tried another design too.

![mockup 2 - 75 image](https://cloud.githubusercontent.com/assets/3889292/7238253/cd0e9da4-e755-11e4-8b18-c31d20e7b8b7.png)

But I feel the First one is more powerful. Anyway, the person who is creating the list should not need to know the description of the person. Let me know what do you guys think.

**Comment by guptapiyush** [comment]
I rethought on the first design and came up with the below design.

![mockup 1 - 90 image simpler](https://cloud.githubusercontent.com/assets/3889292/7238596/4ac2fac2-e758-11e4-9040-0203d120748d.png)

I think this one has two advantages
1. Story is self explanatory - You don't need to check what does '?' sign mean.
2. In my list if I have 6 names and 5 of them reflect large icons of Story, I'll be motivated to eliminate those yellow color buttons.

**Comment by sanjusoftware** [comment]
@guptapiyush can we close this one now? for showing someone os online we should ideally have another story for that

**Comment by gakshay** [comment]
implemented, may add another story for design related changes
