### ISSUE TITLE
Add story to why would you like to connect

### ISSUE THREAD

**Issue by vikrambahl** [gakshay/hookhook#23]
Please add a feature where you can specify why would you like to meet somebody or what is the request all about

**Comment by vikrambahl** [comment]
There should be a story button on all those tiles which don't have a story. When I click on them, it would give me a pop-up where I can add the story and the label
![pinterestui](https://cloud.githubusercontent.com/assets/5754037/7206603/b097763e-e550-11e4-8ccb-862528a1f27b.png)

**Comment by guptapiyush** [comment]
I'm uploading the design of how the actual screens may look like.

![story screen 1](https://cloud.githubusercontent.com/assets/3889292/7239701/ca11fdc0-e760-11e4-8596-884a73826979.png)
![story screen 2](https://cloud.githubusercontent.com/assets/3889292/7239642/66aa8c02-e760-11e4-80e3-bc36087e94aa.png)
![story screen 3](https://cloud.githubusercontent.com/assets/3889292/7239639/66a7e178-e760-11e4-8ba9-cf9cd4ad564c.png)
![story screen 4](https://cloud.githubusercontent.com/assets/3889292/7239640/66aa0a66-e760-11e4-828c-f851b5435a79.png)

Important Note - I understand that this is a time consuming UI implementation. So Don't bother much with beautifulness of the features. Just create basic framework and we can keep working on it later.

**Comment by gakshay** [comment]
Since we have implemented simpler UI as of now. Closing this story. Will revisit it later once this UI needs to be implemented
