### ISSUE TITLE
Add a label to specify your request

### ISSUE THREAD

**Issue by vikrambahl** [gakshay/hookhook#24]
On every request, a user will be able to add one label that specifies why he wants to meet

**Comment by guptapiyush** [comment]
I have added the mockup in the other Story also. Adding it here again.

![story screen 1](https://cloud.githubusercontent.com/assets/3889292/7239743/2afa2fcc-e761-11e4-9aa8-fdc94f2aad24.png)

**Comment by sanjusoftware** [comment]
done.
