### ISSUE TITLE
Pickup button on Requests

### ISSUE THREAD

**Issue by vikrambahl** [gakshay/hookhook#25]
Pickup button allows for me to add a person on somebody else's wishlist onto my wishlist. For now we just need the button - on hover

**Comment by guptapiyush** [comment]
Since we haven't thought through the workflow from the Hero's and the 3rd user's standpoint. We can work on it later.

**Comment by sanjusoftware** [comment]
![screen shot 2015-05-04 at 12 51 29 pm](https://cloud.githubusercontent.com/assets/232573/7449915/66a45f92-f25c-11e4-9394-5e5185dd1245.png)

this is what we are talking about here.. the "Add to My List" button on someone's profile that you don't already have on your list

**Comment by guptapiyush** [comment]
Yes. This will be visible when
1. I am logged in.
2. The person is already not in my list.
3. The person is already not connected to me as a friend or follower.
