### ISSUE TITLE
Hero: Request acknowledgement flow

### ISSUE THREAD

**Issue by gakshay** [gakshay/hookhook#27]
- [x]  Highchart to show types of requests hero has received
- [x] use highchart community edition
- [x] Remove the highchart branding...Once we get commercial we will need to buy the license

**Comment by gakshay** [comment]
![screen shot 2015-05-04 at 12 16 47 pm](https://cloud.githubusercontent.com/assets/116975/7449652/938ae782-f258-11e4-9f28-22c422362cc3.png)

**Comment by gakshay** [comment]
Done with the changes and it's appearing on request.to

**Comment by guptapiyush** [comment]
Looks pretty impressive. I think this can be closed now.
