### ISSUE TITLE
Hero: Admirer user tile

### ISSUE THREAD

**Issue by gakshay** [gakshay/hookhook#28]
Below is the design of the user tile of an admirer

![screen shot 2015-05-04 at 12 18 24 pm](https://cloud.githubusercontent.com/assets/116975/7449674/f6a3fe58-f258-11e4-8562-1950ac1dc850.png)

**Comment by guptapiyush** [comment]
In our next conversation, we should discuss this tile in detail. We need to make this actionable as the next step.

**Comment by gakshay** [comment]
Cool...For the scope of this story this tile works...for action items different stories can be created...closing then
