### ISSUE TITLE
Bug: The newer items added to the UI are not responding to the Javascript events

### ISSUE THREAD

**Issue by sanjusoftware** [gakshay/hookhook#33]
If a new user added to your dashboard, the story button do not work, the remove button does not appear if you mouse over the new user tile etc.

**Comment by guptapiyush** [comment]
I just added a person in my list today and the size of the image was 4 times the normal ones.

![screen shot 2015-05-11 at 4 39 37 pm](https://cloud.githubusercontent.com/assets/3889292/7577375/5ad9d304-f7fc-11e4-8d79-45354a0dc891.png)

**Comment by guptapiyush** [comment]
I agree how to quickly fix these small bugs? I'm demoing a lot these days and feels kinds awkward.

**Comment by gakshay** [comment]
After adding a new user, close button deletes the user but '+' sign doesn't open up the modal...was it working on your machine @sanjusoftware ?

**Comment by sanjusoftware** [comment]
I forgot about testing that one actually... fixed it now.
