### ISSUE TITLE
Pre-Launch Campaign

### ISSUE THREAD

**Issue by guptapiyush** [gakshay/hookhook#36]
Deadline - ASAP.

We need to start online campaign to let a broad audience know the platform that we are building. Five crucial elements for a campaign are
- [x]  Teaser - We have created the video of our story for this purpose. I shared the video with a few close people in my network for their first reaction and optimized the video further on the basis of feedback. Overall, people are connecting well with the video.
1. Online Promotion - I have on boarded a fellow classmate (a Chinese student) to help me in this process. She will be working full time on this for next 3 months in lieu to her internship. Her background is event marketing and seems to be well connected with the idea.
- [x]  Website Readiness - Our website must show relevant content and accept user's data. I designed the landing page for two kind of users that we may expect. First kind don't want to spend much time but still want to be notified for the early access. Second kind would be willing to work with us, so I called these users as "Founding Users".
- [x] Benefit Scheme for Early Users - Founding User FAQ document is ready and I have uploaded it on the Request's Slideshare account http://www.slideshare.net/requestto/founding-user-faqs
1. Analytics - We need to incorporate analytics on website to track traffic, user behavior and an easy way for me to see the data anytime I want it.

Once people share their data, we can select relevant users and on board them privately in addition to users that I'm already talking to personally.

Points 3 & 5 are the critical to start our pre-launch campaign. The designs and images were shared on slack yesterday. Screenshots with a few subtle changes are attached

For Early Users
![landing page 1](https://cloud.githubusercontent.com/assets/3889292/7578178/7f660be8-f806-11e4-9cf9-ca336717ef35.png)

For Founding Users
![landing page 2](https://cloud.githubusercontent.com/assets/3889292/7578179/825cca08-f806-11e4-8722-e51e3f250342.png)

**Comment by gakshay** [comment]
@sanjusoftware can you take a stab at making this page prettier now on Campaign branch to have video and both forms in single page view...I will work on analytics, and email there after...
