### ISSUE TITLE
The user twitter profile details like image, des etc should be updated in case it gets updated on twitter

### ISSUE THREAD

**Issue by sanjusoftware** [gakshay/hookhook#38]
The reason for this story is that as we are storing the image URL, description etc in our local database, if the user changes the pic on Twitter, it won;t get updated on our local and that might cause the image not to appear anymore on the site. Its happening for my account as well right now. The older image is not there and my new image doesn't show up anymore.

points to consider:
1. When should these updates happen?
2. Should we stop storing these details and rather get it from Twitter

**Comment by gakshay** [comment]
How about store the URL for image but on error fetch the image URL on run time and save it..fetching all the user data from twitter will 1. make it slow 2. We have a limit on number of API calls an application can make in an hour

**Comment by sanjusoftware** [comment]
the url does not through an error in the application.. it only will happen on the browser... r u saying we should handle that ?

**Comment by guptapiyush** [comment]
What's the final status on this? Is this resolved in some way?
