### ISSUE TITLE
 We need to show a 3x3 matrix.

### ISSUE THREAD

**Issue by sanjusoftware** [gakshay/hookhook#45]
I actually intend to get 9 people to stay in sync with mobile design. We need to show a 3x3 matrix. This will also free up the space on the right side. We can incorporate other useful messaging in the free space. Show the slots as 3x3 matrix.

**Comment by sanjusoftware** [comment]
this ones is fixed now

**Comment by gakshay** [comment]
I have marked the max limit back to 9 now on the default LIST..in order to show 3x3 matrix...looks good now
