### ISSUE TITLE
Bug - Cannot browse any user's profile.

### ISSUE THREAD

**Issue by guptapiyush** [gakshay/hookhook#48]
Currently, clicking any user's name is redirecting back me to my own profile. Need a fix asap.

**Comment by sanjusoftware** [comment]
@guptapiyush I cannot reproduce this bug on request.to.. can u add more info which page r u seeing this.. an example will help more

**Comment by gakshay** [comment]
@sanjusoftware Any user login using other than twitter login may have that behavior as there is no twitter handle. I tried redeploying on QA its already updated..can you check the get_user method in Application Controller on QA branch...I did some change but have to leave for India in sometime.

**Comment by gakshay** [comment]
closing as this one got fixed
