### ISSUE TITLE
New Explore View

### ISSUE THREAD

**Issue by guptapiyush** [gakshay/hookhook#50]
With the new tile view, I believe the new Explore view would look a lot like the design below. Few important notes
- [x]  Only show three Hero's for each person.
- [x] We need a "Follow" button to follow wha's happening in the lives of people who are on this platform.
- [x] Give enough spacing such that only two users are visible in one page. This reduces the visual load on the mind. People can now take their time to engage with the content lot more comfortably.

Screenshot attached.
![screen shot 2015-06-14 at 8 01 40 pm](https://cloud.githubusercontent.com/assets/3889292/8152297/34c1055e-12d0-11e5-8713-868dfb285e5e.png)

**Comment by guptapiyush** [comment]
Some thoughts. Use as many words as possible at this stage.
1. We have used an icon for Help - Instead use the word "Help" itself. Otherwise too many things for users to learn about.
2. Hide "Add to" button for now as we don't have much action anyway. Looks like too many options right now.
3. Eliminate Like button. It looks like the replica of Facebook like icon. Simply use the word "Like". Nobody can claim right on the word.
4. User name is not visible currently. Show it.
5. We also don't have Follow button but that is okay for now. We'll prioritize it later.

**Comment by sanjusoftware** [comment]
all the items in this issue are done now.. so closing the issue
