### ISSUE TITLE
Feed Views for 0 Admirer Case

### ISSUE THREAD

**Issue by guptapiyush** [gakshay/hookhook#52]
Let's show one Admirer to every user who signs up on the platform and that will be me. This will give each user a feel of how admirer's request feed will look like.
1. Summary View

![screen shot 2015-06-23 at 5 54 50 pm](https://cloud.githubusercontent.com/assets/3889292/8320534/071f7a74-19d1-11e5-86a1-464beddba7df.png)
1. Feed View

![screen shot 2015-06-23 at 5 55 00 pm](https://cloud.githubusercontent.com/assets/3889292/8320536/0ed23b08-19d1-11e5-8b16-45a0e7e619be.png)
1. Feed View (Expanded)

![screen shot 2015-06-23 at 5 55 09 pm](https://cloud.githubusercontent.com/assets/3889292/8320537/14aff6b4-19d1-11e5-9983-97088dc4ae8c.png)

Let me know if there are any thoughts.

**Comment by gakshay** [comment]
I like you being the default admirer of any new user.. :)

**Comment by guptapiyush** [comment]
Status?

**Comment by gakshay** [comment]
Me and Sanjeev had a discussion on it.. seems graph may make sense, on next iteration...as new feature...thoughts?

**Comment by gakshay** [comment]
@pgworld: As soon a user is created in our system, you will start admiring…is this flow correct? Or when a user adds first user to his RequestBook you start admiring that user?

Thing is as soon as X user add a Y user from twitter this Y user is also created in our system and you start admiring Y even though that user is just added by X...

how about as soon as user adds 3 people to his board..CEO starts admiring and one can converse with pgworld…??

Anyways enabled you as default admirer as of now as soon as a new user is added in the system. Easy and quick

**Comment by guptapiyush** [comment]
1. I'm okay with Graph implementation delay but I thought that you had already implemented that. Why do you wanna delay it?
2. Yeh I want to be the admirer immediately a person has signed up. No waiting for any action. The point is that my admiration can't be the incentive for the user but a high point to take more actions.

**Comment by gakshay** [comment]
request.to will the default admirer...closing this one...and will deploy those changes on production for default admirer

**Comment by gakshay** [comment]
between graph has been disabled as of now with no links...will enable and test whenever required
