### ISSUE TITLE
User Profile Enhancements

### ISSUE THREAD

**Issue by guptapiyush** [gakshay/hookhook#55]
1. It should be "Hi, I'm Piyush Gupta"
2. "Add to my List" button should be renamed as "Request"

![screen shot 2015-06-30 at 8 19 20 pm](https://cloud.githubusercontent.com/assets/3889292/8446888/5ad809a8-1f65-11e5-83f7-d3e5519c6417.png)

**Comment by gakshay** [comment]
Currently ADD TO MY LIST changes to following when a user clicks..

Making it to REQUEST and when showing FOLLOWING doesn't make sense...need to think of proper wording

**Comment by gakshay** [comment]
Currently making it to:

![image](https://cloud.githubusercontent.com/assets/116975/8510418/fab1ccc4-22fe-11e5-8b65-8708404995a4.png)

![image](https://cloud.githubusercontent.com/assets/116975/8510420/07bdaf0a-22ff-11e5-9a17-b26f1cc265b7.png)

**Comment by gakshay** [comment]
After discussion doing this..

![image](https://cloud.githubusercontent.com/assets/116975/8510461/fbad9834-2302-11e5-9af5-aab1548902bc.png)

![image](https://cloud.githubusercontent.com/assets/116975/8510464/0339b114-2303-11e5-87ee-75bcb5b62f9b.png)
