### ISSUE TITLE
List of Bugs

### ISSUE THREAD

**Issue by guptapiyush** [gakshay/hookhook#57]
- [x] Remove this authentication Acknowledgement. It doesn't serve any purpose.
  <img width="1158" alt="screen shot 2015-07-06 at 4 36 59 pm" src="https://cloud.githubusercontent.com/assets/3889292/8537285/be123858-2411-11e5-8c83-452fb80df798.png">
- [x] Notice some bugs on the tile.
  <img width="335" alt="screen shot 2015-07-06 at 7 10 24 pm" src="https://cloud.githubusercontent.com/assets/3889292/8537364/b8915868-2412-11e5-9b35-7946dad7b1df.png">
- [x]  Change these Names and Bring a Default Number '0' to them. So, helped remains helped, While hooked changes to either "responses", "conversations". I prefer conversations.
  <img width="290" alt="screen shot 2015-07-06 at 6 08 30 pm" src="https://cloud.githubusercontent.com/assets/3889292/8537380/09fd24d4-2413-11e5-87aa-51c8325193b2.png">
- [x] We need to say, 'X people I strongly admire'. "Strong" is a very important signal in our product.
  <img width="286" alt="screen shot 2015-07-06 at 6 08 39 pm" src="https://cloud.githubusercontent.com/assets/3889292/8537394/31ebb50a-2413-11e5-9895-d2b535a64df0.png">
- [x]  Tiles are behaving randomly. But refreshing the page solves the problem. If it requires time, then just leave it.
  <img width="435" alt="screen shot 2015-07-06 at 7 18 13 pm" src="https://cloud.githubusercontent.com/assets/3889292/8537438/c81a4870-2413-11e5-8975-3e24bbca6f6d.png">

**Comment by gakshay** [comment]
Closing as all the issues are fixed..if there are issues with the tiles...we need to look that separately
