### ISSUE TITLE
Fix - Default admirer text change

### ISSUE THREAD

**Issue by guptapiyush** [gakshay/hookhook#66]
Look at this message from Purva

<img width="691" alt="screen shot 2015-07-21 at 1 10 05 am" src="https://cloud.githubusercontent.com/assets/3889292/8795875/7eb8775a-2f45-11e5-8a78-f8aca1a7428b.png">

The new text could be:
Warm welcome to Request.to and I hope that you will find it useful. If you have any feedback/ suggestion/ new ideas/ wild thoughts at any time, please shoot them to me at piyush@request.to. I'm all ears. We have pledged that we'll not rest unless you come back to us and say, 'wow'.

**Comment by gakshay** [comment]
![image](https://cloud.githubusercontent.com/assets/116975/8797821/9566be8c-2fbb-11e5-9efe-5b76a957197a.png)

closing
